name: Release
on:
  release:
    types: [ released ]
jobs:
  prepare:
    name: Checkout & Test
    runs-on: ubuntu-latest
    steps:
      - name: Install zsh
        run: sudo apt-get update; sudo apt-get install zsh
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Unit Tests
        run: |
          ./project test -c coverage.out -H coverage.html -j unit_test.json
      - uses: actions/upload-artifact@v4
        with:
          name: project-reports
          path: |
            .reports/
  sonarcloud:
    name: SonarCloud
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/download-artifact@v4
        with:
          name: project-reports
          path: .reports/
      - name: Version
        run: |
          echo "sonar.projectVersion=${{ github.event.release.name }}"
          echo "sonar.projectVersion=${{ github.event.release.name }}" >> sonar-project.properties
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
